spring:
  application:
    name: gatewayservice
 

  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/book/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
 
  
  
server:
  port: 8087

